# Generated by Django 5.1.4 on 2025-01-19 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_skill_proficiency_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('showPhone', models.BooleanField(default=True)),
                ('showEmail', models.BooleanField(default=True)),
                ('showAddress', models.BooleanField(default=True)),
                ('tailoredSummary', models.TextField(blank=True, null=True)),
                ('certifications', models.ManyToManyField(related_name='resume_certifications', to='myapp.certification')),
                ('educations', models.ManyToManyField(related_name='resume_educations', to='myapp.education')),
                ('skills', models.ManyToManyField(related_name='resume_skills', to='myapp.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('tailoredDescription', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.project')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.resume')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='projects',
            field=models.ManyToManyField(related_name='resume_projects', through='myapp.ResumeProject', to='myapp.project'),
        ),
        migrations.CreateModel(
            name='ResumeWorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('tailoredDescription', models.TextField(blank=True, null=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.resume')),
                ('workExperience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.workexperience')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='workExperiences',
            field=models.ManyToManyField(related_name='resume_work_experiences', through='myapp.ResumeWorkExperience', to='myapp.workexperience'),
        ),
    ]
