# Generated by Django 5.1.4 on 2025-01-22 01:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_coverletter_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
