# Generated by Django 5.1.4 on 2025-01-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_coverletter_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='portfolio_url',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
