from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from myapp.models import *
from enum import Enum
import google.generativeai as genai
import json
from .json_views import *


GEMINI_API_KEY = "AIzaSyB2TP2FCbiYgH-wSJcjvRuoiV8GwVWkFiM"
GEMINI_MODEL = "gemini-1.5-flash-8b"

CURRENT_REQUEST = None

COVER_LETTER_DATA = {
    "name": "Example AI Cover Letter",
    "purpose": "To demonstrate how a cover letter could be generated using AI",
    "text": "The text body of the coverletter would be here, generated by AI and tailored to the job or description you provided",
}


@login_required
def ai_cover_letter_modal(request):
    if request.method != 'POST':
        return render(request, 'frontend/modals/ai_cover_letter_modal.html')


    global CURRENT_REQUEST

    CURRENT_REQUEST = request

    cover_letter_description = request.POST.get("cover_letter_description")

    if not cover_letter_description:
        return JsonResponse({ "error": "A cover_letter_description must be provided" })

    # Define the AI's functions
    ai_tools = [
        set_cover_letter_name_and_purpose,
        set_cover_letter_text
    ]

    # Initalize the AI chat
    genai.configure(api_key=GEMINI_API_KEY)
    model = genai.GenerativeModel(model_name=GEMINI_MODEL, tools=ai_tools)
    chat = model.start_chat(enable_automatic_function_calling=True)

    # Purpose and Name
    next_command = f"""
        This is an automated process to walk you through creating a cover letter. 
        Follow resume best practices. 
        Do not hallucinate information. 
        Do not call a function you are not explicitly asked to call. 

        This is a description of the purpose of the cover letter. It could also be a job description, 
        in that case you should assume the resume's purpose is to be tailored to that job:

        {cover_letter_description} 

        Call the 'set_cover_letter_name_and_purpose' function to define the name and purpose of this cover letter.
    """
    response = chat.send_message(next_command)

    # Get user info
    user_info = get_data(EntityType.USER)
    user_education = get_data(EntityType.EDUCATION)
    user_work_experience = get_data(EntityType.WORK_EXPERIENCE)
    user_skills = get_data(EntityType.SKILLS)
    user_projects = get_data(EntityType.PROJECTS)
    user_certifications = get_data(EntityType.CERTIFICATIONS)

    # Summary
    next_command = f"""
        Here is all the information you need to know about the person you are completing this cover letter for. 

        Personal Information: 
        {user_info} 

        Education: 
        {user_education} 

        Work Experience: 
        {user_work_experience}

        Skills: 
        {user_skills}

        Projects: 
        {user_projects} 

        Certifications: 
        {user_certifications} 

        When writing the cover letter:
        
        Do not include any placeholders such as [Hiring Manager Name], [Platform where you saw the ad], etc. You should use language that avoids placeholders since everything you need should be here. 
        Use professional, but common language. Do not use words that are not commonly used. 
        Do not halucinate any information about the applicant, all information should be sourced from the provided information. 
        Keep the cover letter an appropriate length, typically 2-5 paragraphs. 
        Keep in mind the purpose described earlier. 

        Call the 'set_cover_letter_text' function to create the cover letter, strictly follow all instructions I have provided.
    """
    response = chat.send_message(next_command)

    return add_cover_letter(request, COVER_LETTER_DATA) # Strange error in this file where the request body is not accessible to the view



# User Info Gathering Functions 

class EntityType(Enum):
    USER = "user"
    EDUCATION = "education"
    WORK_EXPERIENCE = "work_experience"
    SKILLS = "skills"
    PROJECTS = "projects"
    CERTIFICATIONS = "certifications"
    
def get_data(entity_type: EntityType):
    """
    Get data for a specific entity type.
    Args:
        entity_type (EntityType): The type of entity to fetch.
    Returns:
        dict: Data corresponding to the specified entity type.
    """
    global CURRENT_REQUEST

    if entity_type == EntityType.USER:
        data = user_info_data(CURRENT_REQUEST)
    elif entity_type == EntityType.EDUCATION:
        data = education_data(CURRENT_REQUEST)
    elif entity_type == EntityType.WORK_EXPERIENCE:
        data = work_experience_data(CURRENT_REQUEST)
    elif entity_type == EntityType.SKILLS:
        data = skill_data(CURRENT_REQUEST)
    elif entity_type == EntityType.PROJECTS:
        data = project_data(CURRENT_REQUEST)
    elif entity_type == EntityType.CERTIFICATIONS:
        data = certification_data(CURRENT_REQUEST)
    else:
        raise ValueError(f"Unknown entity type: '{entity_type}'")

    return json.loads(data.content.decode('utf-8'))



# AI Tools

def set_cover_letter_name_and_purpose(name:str, purpose:str):
    """
    Sets the name and purpose of the cover letter you are currently creating.
    Args:
        name: The name of this cover letter
        purpose: A very brief description of what this cover letter will be used for
    """
    global COVER_LETTER_DATA
    COVER_LETTER_DATA['name'] = name
    COVER_LETTER_DATA['purpose'] = purpose

def set_cover_letter_text(text:str):
    """
    Sets the text of the cover letter you are currently creating.
    Args:
        text: The body of the cover letter, the actual cover letter itself.
    """
    global COVER_LETTER_DATA
    COVER_LETTER_DATA['text'] = text



# Other Views

@login_required
def cover_letter_delete(request):
    cover_letter_id = request.GET.get('id')

    if not cover_letter_id:
        return JsonResponse({"error": "Cover letter ID is required."}, status=400)

    # Ensure the resume belongs to the current user
    cover_letter = get_object_or_404(CoverLetter, id=cover_letter_id, user=request.user)

    cover_letter.delete()

    return JsonResponse({"message": "Cover letter deleted successfully!", "status": "success"}, status=200)


@login_required
def cover_letter_modal(request):
    if request.method != 'POST':
        cover_letter = None

        cover_letter_id = request.GET.get('id')
        if cover_letter_id:
            cover_letter = get_object_or_404(request.user.cover_letters, id=cover_letter_id)

        context = {
            'coverletter': cover_letter
        }

        return render(request, 'frontend/modals/cover_letter_modal.html', context)

    print("Received a POST request to add a cover letter")

    return add_cover_letter(request, request.POST.dict()) # Strange error in this file where the request body is not accessible to the view


@login_required
def add_cover_letter(request, data=None):
    try:
        if not data:
            data = json.loads(request.body) # Strange error in this file where the request body is not accessible to the view

        cover_letter = CoverLetter.objects.create(
                user=request.user,
                name=data.get('name', 'Untitled Cover Letter'),
                purpose=data.get('purpose', ''),
                text=data.get('text', ''),
            )

        cover_letter.save()

        return JsonResponse({'status': 'success', 'message': 'Cover Letter created successfully.', 'cover_letter_id': cover_letter.id})

    except json.JSONDecodeError:
        return JsonResponse({'status': 'error', 'message': 'Invalid JSON format.'}, status=400)
    except KeyError as e:
        return JsonResponse({'status': 'error', 'message': f'Missing key: {e}'}, status=400)
    except Exception as e:
        return JsonResponse({'status': 'error', 'message': f'An error occurred: {str(e)}'}, status=500)