version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map container's port 8000 to local port 8000
    volumes:
      - .:/app  # Mount the local project directory to the container
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
